meta_product_name: "Human Beans"
meta_title: "Human Beans - Help your children to become better human beans."
meta_description: "Human Beans is a management tool for chores, making it easier for parents to create, assign and monitor chores through gamification and rewards system."
meta_image: "family_static.png"
